cars/urls.py
from django.urls import path
from .views import *

app_name = 'cars'

urlpatterns = [
    path("", home, name="home_view"),
    path("about/", about, name="about_view"),
    path("car-list/", car_list, name="car_list"),
]

rental_car/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
     path("", include("cars.urls")),
     path("", include("rentals.urls")),
     path("", include("users.urls")),
     path("", include("cart.urls")),


     # password Change
    path('password_change/' , auth_views.PasswordChangeView.as_view() , name='password_change'), #as_view is used for class based views cuz passwordchangeview is django builtin vie which is class-based view
    path('password_change/done/' , auth_views.PasswordChangeDoneView.as_view() , name='password_change_done'), 
    #password Reset
    path('password_reset/' , auth_views.PasswordResetView.as_view() , name='password_reset'), 
    path('password_reset/done/' , auth_views.PasswordResetDoneView.as_view() , name='password_reset_done'), 
    path('reset/<uidb64>/<token>' , auth_views.PasswordResetConfirmView.as_view() , name='password_reset_confirm'), 
    path('reset/done/' , auth_views.PasswordResetCompleteView.as_view() , name='password_reset_complete'), 
]
 # there is password manage process given below:

    # password_change
    # password_change_done

    # password_reset
    # password_reset_done
    # password_reset_confirm
    # password_reset_complete

# Serving media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path("register/", user_register_view, name="user_register_view"),
    path("login/", user_login_view, name="user_login_view"),
    path("logout/", user_logout_view, name="user_logout_view"),
    path("profile/", user_profile_detail_view, name="user_profile_detail_view"),
    path("profile/edit/", user_profile_edit_view, name="user_profile_edit_view"),
    path("users/verify_email/<str:token>/", verify_email_view, name="verify_email"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />
  
    <title>Rent A Car</title>
  
    <!-- slider stylesheet -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  
    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
  
    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,600,700&display=swap" rel="stylesheet">
  
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <!-- responsive style -->
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />

  <!-- Icon Font Stylesheet -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
  
  <title>{% block title %}{% endblock title %}</title>
  {% block css %}{% endblock css %}
  {% block javascript %}{% endblock javascript%}
  
</head>
<body>
  {% block content %}

  {% endblock content %}
  {% include "footer.html" %}


  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>

</body>

</html>

templates/footer.html
  <!-- footer section -->
  <footer class="container-fluid footer_section">
    <p>
      Copyright &copy; 2020 All Rights Reserved.
    </p>
  </footer>
  <!-- footer section -->

templates/header.html
    <!-- header section strats -->
    <header class="header_section">
        <div class="container-fluid">
          <nav class="navbar navbar-expand-lg custom_nav-container">
            <a class="navbar-brand" href="{% url "cars:home_view" %}">
              <span class="logo">
                Rent A Car
              </span>
            </a>
  
            <div class="navbar-collapse" id="">
              <div class="user_option">
                {% if user.is_authenticated %}
                <a href="{% url "users:user_logout_view" %}">Logout</a>
                {% else %}
                <a href="{% url "users:user_login_view" %}">Login</a>
                {% endif %}
              </div>
              <div class="custom_menu-btn">
                <button onclick="openNav()">
                  <span class="s-1"> </span>
                  <span class="s-2"> </span>
                  <span class="s-3"> </span>
                </button>
              </div>
              <div id="myNav" class="overlay">
                <div class="overlay-content">
                  <a href="{% url "cars:home_view" %}">Home</a>
                  <a href="{% url "cars:about_view" %}">About</a>
                  <a href="{% url "cars:car_list" %}">Cars</a>
                  {% if user.is_authenticated %}
                  <a href="{% url "users:user_profile_detail_view" %}">Your Profile</a>
                  <a href="{% url "password_change" %}">Change Password</a>
                  {% endif %}
                  <a href="http://127.0.0.1:8000/#contact-us">Contact Us</a>
                  {% if user.is_authenticated %}
                  <a href="{% url "users:user_logout_view" %}">Logout</a>
                  {% else %}
                  <a href="{% url "users:user_login_view" %}">Login</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </nav>
        </div>
      </header>
      <!-- end header section -->